project_id = "huigwbyctzjictnaycjj"

[functions.send-dm-notification]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = true

[functions.import-clubs]
verify_jwt = true

[functions.didit-session]
verify_jwt = true

[functions.didit-webhook]
verify_jwt = false

[functions.cleanup-venues]
verify_jwt = true

[functions.algolia-sync]
verify_jwt = true

[functions.algolia-search]
verify_jwt = false

[functions.translate-i18n]
verify_jwt = true
