project_id = "huigwbyctzjictnaycjj"

[functions.send-notification]
verify_jwt = true

[functions.import-clubs]
verify_jwt = true

[functions.didit-session]
verify_jwt = true

[functions.didit-webhook]
verify_jwt = false
